{{- if .Values.agent.enabled -}}
apiVersion: {{ .Values.agent.apiVersion }}
kind: Agent
metadata:
  name: {{ .Values.agent.name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "analysis-agent.agent.labels" . | nindent 4 }}
spec:
  # Reference to ModelConfig in Kagent namespace
  modelConfig: {{ .Values.kagent.modelConfig }}

  # System instructions for the agent
  instructions: |
{{ .Values.agent.instructions | nindent 4 }}

  # Custom Python tools
  tools:
{{- toYaml .Values.agent.tools | nindent 4 }}

  # Service account for Kubernetes API access
  serviceAccount: {{ include "analysis-agent.agent.serviceAccountName" . }}

  # Agent memory volume mount
  volumes:
    - name: agent-memory
      persistentVolumeClaim:
        claimName: {{ .Values.storage.pvc.name }}

  volumeMounts:
    - name: agent-memory
      mountPath: /agent-memory
{{- end }}
