{{- if .Values.agent.enabled -}}
apiVersion: {{ .Values.agent.apiVersion }}
kind: Agent
metadata:
  name: {{ .Values.agent.name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "analysis-agent.agent.labels" . | nindent 4 }}
spec:
  declarative:
    modelConfig: {{ .Values.kagent.modelConfig }}
    systemMessage: |
{{ .Values.agent.instructions | nindent 6 }}
    deployment:
      replicas: 1
      resources:
        requests:
          cpu: 100m
          memory: 256Mi
        limits:
          cpu: 1000m
          memory: 1Gi
      volumes:
        - name: agent-memory
          persistentVolumeClaim:
            claimName: {{ .Values.storage.pvc.name }}
      volumeMounts:
        - name: agent-memory
          mountPath: /agent-memory
{{- end }}
