{{- if .Values.notifier.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: notifier-service
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "analysis-agent.notifier.labels" . | nindent 4 }}
spec:
  type: {{ .Values.notifier.service.type }}
  ports:
    - port: {{ .Values.notifier.service.port }}
      targetPort: {{ .Values.notifier.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    app: notifier-service
    {{- include "analysis-agent.selectorLabels" . | nindent 4 }}
{{- end }}
