{{- if .Values.notifier.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notifier-service
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "analysis-agent.notifier.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.notifier.replicaCount }}
  selector:
    matchLabels:
      app: notifier-service
      {{- include "analysis-agent.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: notifier-service
        {{- include "analysis-agent.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "analysis-agent.notifier.serviceAccountName" . }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: notifier
        image: "{{ .Values.notifier.image.repository }}:{{ .Values.notifier.image.tag }}"
        imagePullPolicy: {{ .Values.notifier.image.pullPolicy }}
        ports:
        - name: http
          containerPort: {{ .Values.notifier.service.targetPort }}
          protocol: TCP
        env:
        - name: SMTP_HOST
          value: {{ .Values.notifier.email.smtpHost | quote }}
        - name: SMTP_PORT
          value: {{ .Values.notifier.email.smtpPort | quote }}
        - name: SMTP_USERNAME
          valueFrom:
            secretKeyRef:
              name: gmail-credentials
              key: username
        - name: SMTP_PASSWORD
          valueFrom:
            secretKeyRef:
              name: gmail-credentials
              key: password
        - name: FROM_ADDRESS
          valueFrom:
            secretKeyRef:
              name: gmail-credentials
              key: from-address
        - name: RECIPIENTS_CRITICAL
          valueFrom:
            secretKeyRef:
              name: email-recipients
              key: recipients-critical
        - name: RECIPIENTS_WARNING
          valueFrom:
            secretKeyRef:
              name: email-recipients
              key: recipients-warning
        - name: RECIPIENTS_INFO
          valueFrom:
            secretKeyRef:
              name: email-recipients
              key: recipients-info
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 10
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          {{- toYaml .Values.notifier.resources | nindent 10 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
