{{- if .Values.webhook.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webhook-service
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "analysis-agent.webhook.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.webhook.replicaCount }}
  selector:
    matchLabels:
      app: webhook-service
      {{- include "analysis-agent.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: webhook-service
        {{- include "analysis-agent.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "analysis-agent.webhook.serviceAccountName" . }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: webhook
        image: "{{ .Values.webhook.image.repository }}:{{ .Values.webhook.image.tag }}"
        imagePullPolicy: {{ .Values.webhook.image.pullPolicy }}
        ports:
        - name: http
          containerPort: {{ .Values.webhook.service.targetPort }}
          protocol: TCP
        env:
        {{- range .Values.webhook.env }}
        - name: {{ .name }}
          value: {{ .value | quote }}
        {{- end }}
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 10
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          {{- toYaml .Values.webhook.resources | nindent 10 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
