{{- if .Values.webhook.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: webhook-service
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "analysis-agent.webhook.labels" . | nindent 4 }}
spec:
  type: {{ .Values.webhook.service.type }}
  ports:
    - port: {{ .Values.webhook.service.port }}
      targetPort: {{ .Values.webhook.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    app: webhook-service
    {{- include "analysis-agent.selectorLabels" . | nindent 4 }}
{{- end }}
