---
# Webhook Service Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webhook-service
  namespace: analysis-agent
  labels:
    app: devops-rca
    component: webhook-service
spec:
  replicas: 2  # HA for webhook receiver
  selector:
    matchLabels:
      app: devops-rca
      component: webhook-service
  template:
    metadata:
      labels:
        app: devops-rca
        component: webhook-service
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/metrics"
    spec:
      serviceAccountName: webhook-sa

      containers:
      - name: webhook
        image: your-dockerhub/analysis-agent-webhook:v0.1.0
        imagePullPolicy: Always

        ports:
        - containerPort: 8080
          name: http
          protocol: TCP

        env:
        - name: LOG_LEVEL
          value: "INFO"
        - name: KAGENT_API_URL
          value: "http://kagent-api.analysis-agent.svc.cluster.local/api/v1/agents/devops-rca-agent/invoke"
        - name: PORT
          value: "8080"

        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"

        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3

        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 3

        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL

---
# Webhook Service
apiVersion: v1
kind: Service
metadata:
  name: webhook-service
  namespace: analysis-agent
  labels:
    app: devops-rca
    component: webhook-service
spec:
  type: ClusterIP
  selector:
    app: devops-rca
    component: webhook-service
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    name: http
  sessionAffinity: None
